# SQLite
SQLite is a relational database management system (RDBMS) contained in a C library. In contrast to many other database management systems, SQLite is not a client–server database engine. Rather, it is embedded into the end program. For the purpose of this notebook i used the car data prediction dataset from kaggle. I splitted the dataset into train and test sets then extracted the testset as a csv file which i then directed to my SQLite browser and saved the data as testdata.db. I took this data back to my jupyter notebbok, imported necessary SQL dependencies and Queried my database.

In [1]:
import numpy as np
import pandas as pd

#### Import car dataset

In [2]:
car_data = pd.read_csv('CarPrice_Assignment.csv')

#### Data manipulation

In [3]:
car_data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
car_data[['aspiration', 'carbody']].head()

  aspiration      carbody
0        std  convertible
1        std  convertible
2        std    hatchback
3        std        sedan
4        std        sedan

In [5]:
car_data.head(20)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167
10,11,2,bmw 320i,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000
11,12,0,bmw 320i,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000
12,13,0,bmw x1,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000
13,14,0,bmw x3,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105.000
14,15,1,bmw z4,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000
15,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760.000
16,17,0,bmw x5,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315.000
17,18,0,bmw x3,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880.000
18,19,2,chevrolet impala,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151.000
19,20,1,chevrolet monte carlo,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295.000

#### Split dataset into train and test set

In [6]:
X = car_data.drop('price', axis=1).values
y = car_data["price"].values

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
X_test

array([[16, 0, 'bmw x4', ..., 5400, 16, 22],
       [10, 0, 'audi 5000s (diesel)', ..., 5500, 16, 22],
       [101, 0, 'nissan nv200', ..., 5200, 27, 34],
       ...,
       [77, 2, 'mitsubishi mirage', ..., 5500, 37, 41],
       [145, 0, 'subaru r1', ..., 4800, 24, 25],
       [105, 3, 'nissan teana', ..., 5200, 19, 25]], dtype=object)

In [10]:
X_test.shape

(62, 25)

#### Convert X test from numpy array to pandas DataFrame

In [12]:
testdata = pd.DataFrame(X_test, columns=['car_ID','symboling','CarName','fueltype','aspiration','doornumber','carbody','drivewheel','enginelocation','wheelbase',
                                  'carlength',
                                  'carwidth',
                                  'carheight',
                                  'curbweight',
                                  'enginetype',
                                  'cylindernumber',
                                  'enginesize',
                                  'fuelsystem',
                                  'boreratio',
                                  'stroke',
                                  'compress',
                                  'horsepower',
                                  'peakrpm',
                                  'citympg','highwaympg'])

In [13]:
testdata.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compress,horsepower,peakrpm,citympg,highwaympg
0,16,0,bmw x4,gas,std,four,sedan,rwd,front,103.5,...,six,209,mpfi,3.62,3.39,8,182,5400,16,22
1,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,five,131,mpfi,3.13,3.4,7,160,5500,16,22
2,101,0,nissan nv200,gas,std,four,sedan,fwd,front,97.2,...,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34
3,133,3,saab 99e,gas,std,two,hatchback,fwd,front,99.1,...,four,121,mpfi,3.54,3.07,9.31,110,5250,21,28
4,69,-1,buick century luxus (sw),diesel,turbo,four,wagon,rwd,front,110,...,five,183,idi,3.58,3.64,21.5,123,4350,22,25

#### Export X test as csv

In [ ]:
#testdata.to_csv('testdata.csv')

#### Import necessary dependencies

In [14]:
import sqlite3 as sql
import pandas as pd
import numpy as np

#### Connect to test database

In [19]:
con = sql.connect("testdata.db")
testdata = pd.read_sql_query("SELECT * from testdata", con)
c=con.cursor()


print(testdata.head())

   Field1  car_ID  symboling                   CarName fueltype aspiration  \
0       0      16          0                    bmw x4      gas        std
1       1      10          0       audi 5000s (diesel)      gas      turbo
2       2     101          0              nissan nv200      gas        std
3       3     133          3                  saab 99e      gas        std
4       4      69         -1  buick century luxus (sw)   diesel      turbo

  doornumber    carbody drivewheel enginelocation  ...  cylindernumber  \
0       four      sedan        rwd          front  ...             six
1        two  hatchback        4wd          front  ...            five
2       four      sedan        fwd          front  ...            four
3        two  hatchback        fwd          front  ...            four
4       four      wagon        rwd          front  ...            five

   enginesize  fuelsystem  boreratio  stroke compress horsepower  peakrpm  \
0         209        mpfi       3.62    3.39     8.00        182     5400
1         131        mpfi       3.13    3.40     7.00        160     5500
2         120        2bbl       3.33    3.47     8.50         97     5200
3         121        mpfi       3.54    3.07     9.31        110     5250
4         183         idi       3.58    3.64    21.50        123     4350

  citympg  highwaympg
0      16          22
1      16          22
2      27          34
3      21          28
4      22          25

[5 rows x 26 columns]

#### Query testdata

In [22]:
c.execute('SELECT enginesize FROM testdata')
print(c.fetchall())

[(209,), (131,), (120,), (121,), (183,), (97,), (110,), (98,), (108,), (97,), (136,), (98,), (140,), (122,), (308,), (92,), (61,), (156,), (122,), (108,), (122,), (181,), (97,), (92,), (90,), (209,), (146,), (141,), (97,), (141,), (183,), (90,), (92,), (173,), (98,), (183,), (108,), (70,), (90,), (156,), (108,), (134,), (120,), (92,), (97,), (110,), (90,), (108,), (152,), (156,), (90,), (171,), (103,), (122,), (97,), (136,), (146,), (70,), (194,), (92,), (108,), (181,)]

In [24]:
c.execute('SELECT enginesize FROM testdata')
z=c.fetchmany(4)
df = pd.DataFrame(z)
print(df)

     0
0  209
1  131
2  120
3  121

In [25]:
c.execute('SELECT enginesize, curbweight, horsepower, carwidth FROM testdata')
y=c.fetchmany(5)
df = pd.DataFrame(y)
print(df)

     0     1    2     3
0  209  3230  182  66.9
1  131  3053  160  67.9
2  120  2302   97  65.2
3  121  2658  110  66.5
4  183  3750  123  70.3

In [26]:
c.execute('SELECT enginesize, curbweight, horsepower, carwidth FROM testdata WHERE enginesize < 120')
x=c.fetchmany(8)
df = pd.DataFrame(x)

print(df)

     0     1   2     3
0   97  2028  69  63.8
1  110  2275  56  64.4
2   98  2140  70  64.4
3  108  2455  94  65.4
4   97  2261  52  65.5
5   98  2204  70  64.0
6   92  2015  62  63.6
7   61  1488  48  60.3